apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: slight-tapir-go 
  janus-idp.io/tekton: slight-tapir-go
  backstage.io/kubernetes-id: slight-tapir-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: slight-tapir-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  