apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: slight-tapir-go-gitops
  description: This is GitOps manifest for slight-tapir-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: slight-tapir-go
    janus-idp.io/tekton: slight-tapir-go 
    backstage.io/kubernetes-id: slight-tapir-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:slight-tapir-go
